# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale          : "en-US"
title           : "Carolina Lucía Gonzalez"
title_separator : "-"
name            : &name "Carolina Lucía Gonzalez"
description     : &description "Computer Scientist"
url             : https://caro811.github.io
baseurl         : "" # the subpath of your site, e.g. "/blog"
repository      : "caro811/caro811.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar        : "Photo.JPG"
  name          : "Carolina Lucía Gonzalez"
  pronouns      : # "(she / her / hers)"
  bio           : "Computer Scientist"
  location      : Geneva, Switzerland # Location
  employer      : # Employer
  uri           : # URL
  email         : "cgonzalez@dc.uba.ar"

  # Academic websites
  arxiv         : # "https://arxiv.org/search/cs?searchtype=author&query=Gonzalez,+C+L"
  googlescholar : "https://scholar.google.com/citations?user=ivyXJf8AAAAJ"
  orcid         : "https://orcid.org/0000-0002-2398-2145"
  researchgate  : "https://www.researchgate.net/profile/Carolina-Gonzalez-66"

  # Repositories and software development
  github        : "caro811"

  # Social media
  linkedin      : "carolina-lucia-gonzalez"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections_dir: collections
collections:
  teaching:
    output: false
  publications:
    output: false
  talks:
    output: false
  projects:
    output: false
  awards:
    output: false
  education:
    output: false
  spoken_languages:
    output: false
  software_skills:
    output: false


# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
